pipeline:
  name: CI-13065-remote
  identifier: CI13065remote
  projectIdentifier: ShobhitTesting
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: ssaccountlevelconnector
        repoName: jhttp
        build:
          type: PR
          spec:
            number: <+trigger.prNumber>
  stages:
    - stage:
        name: CI
        identifier: CI
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: account.Harness_Kubernetes_Cluster
              namespace: harness-delegate-ng
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    connectorRef: account.harnessImage
                    image: alpine
                    shell: Sh
                    command: echo "hello"
