pipeline:
  "on":
    push:
      branches:
        - PipelineConditionsTesting1
    pull_request:
      branches:
        - PipelineConditionsTesting1
  clone:
    disabled: true
  stages:
    - steps:
        - run:
            script: echo "HelloWorld"
