pipeline:
  "on":
    push:
      branches:
        - main
    pull_request:
      branches:
        - main
  clone:
    disabled: true
  stages:
    - steps:
        - run:
            script: echo "hello from main branch"
