pipeline:
  "on":
    push:
      branches:
        - pipeline-8
  clone:
    disabled: true
  stages:
    - id: pipe-8
      delegates: myRunner-Shobhit
      steps:
        - run:
            script: echo "hello from branch pipeline-8.Sync."
