pipeline:
  "on":
    push:
      branches:
        - pipeline-100
    pull_request:
      branches:
        - main
  clone:
    disabled: true
  stages:
    - steps:
        - run:
            script: echo "hello from branch pipeline-10-2.Sync."
