pipeline:
  "on":
    push:
      branches:
        - pipeline-8
    pull_request:
      branches:
        - develop
  clone:
    disabled: true
  stages:
    - steps:
        - run:
            script: echo "hello from branch pipeline-8-1.Sync"
