pipeline:
  "on":
    push:
      branches:
        - pipeline-7
    pull_request:
      branches:
        - main
        - develop
        - master
  clone:
    disabled: true
  stages:
    - steps:
        - run:
            script: echo "hello from branch pipeline-7.Sync"
