pipeline:
  "on":
    push:
      branches:
        - pipeline-9
  clone:
    disabled: true
  stages:
    - steps:
        - run:
            script: echo "hello from branch pipeline-9.Sync. Lets see"
