pipeline:
  "on":
    push:
      branches:
        - pipeline-3
    pull_request:
      branches:
        - main
  clone:
    disabled: true
  stages:
    - steps:
        - run:
            script: echo pipeline-3
