pipeline:
  push:
    branches:
      - develop
      - main
      - master
  pull_request:
    branches:
      - main
  clone:
    disabled: true
  stages:
    - steps:
        - run:
            script: echo "hello from branch 5 and pipeline 5-1"
