pipeline:
  "on":
    push:
      branches:
        - master
    pull_request:
      branches:
        - main
  clone:
    disabled: true
  stages:
    - steps:
        - run:
            script: echo "from branch pipeline-5"
