pipeline:
  "on":
    push:
      branches:
        - master
    pull_request:
      branches:
        - main
        - develop
        - master
  clone:
    disabled: true
  stages:
    - steps:
        - run:
            script: echo "hello from branch pipeline-5"
