pipeline:
  name: testingCond
  identifier: testingCond
  tags: {}
  projectIdentifier: Unified
  orgIdentifier: default
  stages:
    - stage:
        name: rf4
        identifier: rf4
        description: ""
        type: CI
        spec:
          cloneCodebase: false
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: ShobhitK8
              namespace: rf
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    connectorRef: ShobhitDockerConnector
                    image: r4
                    shell: Sh
                    command: r34
