-------
kind: pipeline
type: docker
name: build-secret-gar-push-test

trigger:
  event:
    - push
  branch:
    - pn-build-secret

steps:
  - name: build-secret-gar-push-test
    image: plugins/gcr
    environment:
      ARTIFACTORY_ACCESS_TOKEN:
        from_secret: artifactory_access_token
    settings:
      dockerfile: dockerfiles/build-secret-image/Dockerfile
      dry_run: true
      registry: gcr.io
      repo: nyt-registry-dev/kaniko-gar-test
      json_key:
        from_secret: nyt-registry-dev-gar
      secrets_from_env:
        - ARTIFACTORY_ACCESS_TOKEN=ARTIFACTORY_ACCESS_TOKEN
      tags: latest
