---
kind: pipeline
name: test secret kube
steps:
- commands:
  - echo 1
  environment:
    SAMPLE_KEY:
      from_secret: FOO
  image: node:18
  name: Install Dependencies
- commands:
  - echo $${SAMPLE_KEY}
  environment:
    SAMPLE_KEY:
      from_secret: FOO
  image: node:18
  name: Run Linting
- commands:
  - echo $${SAMPLE_KEY}
  environment:
    SAMPLE_KEY:
      from_secret: FOO
  image: node:18
  name: Run Unit Tests
trigger:
  branch:
    exclude:
    - main
  event:
  - push
type: kubernetes


# ---
# kind: pipeline
# type: docker
# name: default

# platform:
#   os: linux
#   arch: arm64
  
# steps:
# - name: another
#   image: alpine
#   commands:
#   - echo "Hellos"
#   - sleep 2
#   - echo "Done"

# ---
# kind: signature
# hmac: F10E2821BBBEA527EA02200352313BC059445190
