---
kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: another
  image: alpine
  commands:
  - echo "Hello world"
- name: save-to-file
  image: alpine
  environment:
    MY_SECRET:
      from_secret: check
  commands:
    - echo "$MY_SECRET" >> .secrets
    - cat .secrets
    - printenv
- name: cat
  image: alpine
  environment:
    MY_SECRET:
      from_secret: FOO
  commands:
    - echo "$MY_SECRET" >> .secret
    - cat .secrets
    - cat .secret
    - printenv
- name: save-to-file-2
  image: alpine
  environment:
    MY_SECRET_1:
      from_secret: check
  commands:
    - echo "$MY_SECRET_1" >> .secrets_1
    - cat .secrets_1
    - cat .secrets
    - cat .secret
    - printenv   
- name: save-to-file-3
  image: alpine
  commands:
    - cat .secrets_1
    - cat .secrets
    - cat .secret
    - printenv    
