---
kind: pipeline
name: default
type: docker
platform:
  os: linux
  arch: amd64
- commands:
  - mix do ecto.create, ecto.load, ecto.migrate, clickhouse.repl.create, clickhouse.create
  depends_on:
  - install-deps
  - db-connections
  environment:
    CI_ANALYTICS_URL:
      from_secret: CI_ANALYTICS_URL
    CI_ANALYTICS_WRITE_KEY:
      from_secret: CI_ANALYTICS_WRITE_KEY
    CLICKHOUSE_URL: http://user:password@clickhouse:8123
    CODECOV_TOKEN:
      from_secret: CODECOV_TOKEN
    HEX_HOME: /drone/src/.hex
    KIM_TEST_PG_URL: postgres://user:password@postgres:5432/kim_test?ssl=false
    MIX_ENV: test
    MIX_HOME: /drone/src/.mix
    MONGO_HOST: mongodb
    PG_URL: postgres://user:password@postgres:5432
    REBAR_BASE_DIR: /dron/src/.rebar
    REDIS_HOST: redis
    REDIS_URL: redis://redis:6379
    SEARCH_ENGINE_TEST_PG_URL: postgres://user:password@postgres:5432/search_engine_test?ssl=false
    SHELL: /bin/sh
    STRIPE_MOCK_API_BASE_URL: http://stripe-mock:12111/
    STRIPE_MOCK_VERSION: 0.84.0
    TICKETING_TEST_PG_URL: postgres://user:password@postgres:5432/dice_test?ssl=false
  image: harbor.dc.dice.fm/bases/elixir1.13.4:latest
  name: prepare-databases
