---
kind: pipeline
type: docker

platform:
  os: linux
  arch: arm64

name: WMS - YEMEK - STG - 6
workspace:
path: /nv-automations

image_pull_secrets:
- dockerconfigjson

steps:
- name: FCM - View Daily - With Warehouse Filter
  image: alpine
  environment:
    TEST_CASE_ID: C1231011
  commands: 
    - echo hello
    - echo $${TEST_CASE_ID}
