---
kind: pipeline
type: docker

name: WMS - YEMEK - STG - 6
clone:
  disable: true

platform:
  os: linux
  arch: amd64  

trigger:
event:
- promote
target:
- yemek
- fcm
- fcm_yemek
status:
- success
- failure

workspace:
path: /nv-automations

image_pull_secrets:
- dockerconfigjson

steps:
- name: FCM - View Daily - With Warehouse Filter
  image: alpine
  environment:
    TEST_CASE_ID: C1231011
  commands: 
    - echo hello
    - echo $${TEST_CASE_ID}
