---
kind: pipeline
type: kubernetes
name: test secret kube

platform:
  os: linux
  arch: arm64

steps:
- name: Run
  image: alpine
  environment:
    TEST_KUBES:
      from_secret: TESTING
  commands:
    - echo "$${TEST_KUBES}"
    - echo ${{ secrets.TESTING }}


# ---
# kind: pipeline
# type: docker
# name: default

# platform:
#   os: linux
#   arch: arm64
  
# steps:
# - name: another
#   image: alpine
#   commands:
#   - echo "Hellos"
#   - sleep 2
#   - echo "Done"

# ---
# kind: signature
# hmac: F10E2821BBBEA527EA02200352313BC059445190
