---
kind: pipeline
type: kubernetes
name: test secret kube
steps:
- name: RUN
- commands:
  - echo $${SAMPLE_KEY}
  environment:
    SAMPLE_KEY:
      from_secret: FOO
  image: alpine

# ---
# kind: pipeline
# type: docker
# name: default

# platform:
#   os: linux
#   arch: arm64
  
# steps:
# - name: another
#   image: alpine
#   commands:
#   - echo "Hellos"
#   - sleep 2
#   - echo "Done"

# ---
# kind: signature
# hmac: F10E2821BBBEA527EA02200352313BC059445190
