
---
kind: pipeline
name: test secret docker

steps:
- commands:
  - echo 123456782
  environment:
    SAMPLE_KEY:
      from_secret: FOO
  image: alpine
  name: Install Dependencies
- commands:
  - echo $${SAMPLE_KEY}
  environment:
    SAMPLE_KEY:
      from_secret: FOO
  image: alpine
  name: Run Linting
- commands:
  - echo $${SAMPLE_KEY}
  environment:
    SAMPLE_KEY:
      from_secret: FOO
  image: alpine
  name: Run Unit Tests
trigger:
  branch:
    exclude:
    - main
  event:
  - push
type: docker



# ---
# kind: pipeline
# name: test secret kubernetes

# steps:
# - commands:
#   - echo 123456785
#   environment:
#     SAMPLE_KEY:
#       from_secret: FOO
#   image: alpine
#   name: Install Dependencies
# - commands:
#   - echo $${SAMPLE_KEY}
#   environment:
#     SAMPLE_KEY:
#       from_secret: FOO
#   image: alpine
#   name: Run Linting
# - commands:
#   - echo $${SAMPLE_KEY}
#   environment:
#     SAMPLE_KEY:
#       from_secret: FOO
#   image: alpine
#   name: Run Unit Tests
# trigger:
#   branch:
#     exclude:
#     - main
#   event:
#   - push
# type: kubernetes
