---
kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: amd64
  
steps:
- name: another
  image: alpine
  commands:
  - yes "This is a test log line" | head -n 12001

trigger:
  ref:
    - refs/heads/main
    - refs/tags/**
    - refs/pull/**
