---
kind: pipeline
type: docker
name: test secret docker
steps:  
- commands:
  - echo 1
  environment:
    SHOBHIT_ENV:
      from_secret: FOO
  image: node:18
  name: Install Dependencies
- commands:
  - echo $${SHOBHIT_ENV}
  environment:
    SHOBHIT_ENV:
      from_secret: FOO
  image: node:18
  name: Run Linting
- commands:
  - echo $${SHOBHIT_ENV}
  environment:
    SHOBHIT_ENV:
      from_secret: FOO
  image: node:18
  name: Run Unit Tests


# ---
# kind: pipeline
# type: docker
# name: default

# platform:
#   os: linux
#   arch: arm64
  
# steps:
# - name: another
#   image: alpine
#   commands:
#   - echo "Hellos"
#   - sleep 2
#   - echo "Done"

# ---
# kind: signature
# hmac: F10E2821BBBEA527EA02200352313BC059445190
