---
kind: pipeline
type: kubernetes
name: test secret kubernetes

platform:
  os: linux
  arch: arm64


steps:
- name: RUN
  image: alpine
  environment:
    SAMPLE_KEY:
      from_secret: TEST_SECRET
  commands:
  - echo $${SAMPLE_KEY}

# ---
# kind: pipeline
# type: docker
# name: default

# platform:
#   os: linux
#   arch: arm64
  
# steps:
# - name: another
#   image: alpine
#   commands:
#   - echo "Hellos"
#   - sleep 2
#   - echo "Done"

# ---
# kind: signature
# hmac: F10E2821BBBEA527EA02200352313BC059445190
