---
kind: pipeline
type: docker

name: WMS - YEMEK - STG - 6
workspace:
path: /nv-automations

image_pull_secrets:
- dockerconfigjson

- name: FCM - View Daily - With Warehouse Filter
image: alpine
environment:
<<: *env
TEST_CASE_ID: C1231011
commands: echo hello
