---
kind: pipeline
type: kubernetes
name: test secret kube

platform:
  os: linux
  arch: arm64


steps:
- name: Run
  image: alpine
  commands:
    - echo hello
    environment:
      SAMPLE_KEY:
        from_secret: TEST_SECRET
        
- name: Check Secret
  image: alpine
  commands:
    - echo $${SAMPLE_KEY}
    environment:
      SAMPLE_KEY:
        from_secret: TEST_SECRET

# ---
# kind: pipeline
# type: docker
# name: default

# platform:
#   os: linux
#   arch: arm64
  
# steps:
# - name: another
#   image: alpine
#   commands:
#   - echo "Hellos"
#   - sleep 2
#   - echo "Done"

# ---
# kind: signature
# hmac: F10E2821BBBEA527EA02200352313BC059445190
