---
kind: pipeline
type: kubernetes
name: test secret kube

platform:
  os: linux
  arch: arm64

steps:
- name: Run
  image: alpine
  environment:
    SAMPLE_KEY:
      from_secret: TEST_SECRET
  commands:
    - echo hello
    - echo "SAMPLE_KEY is set to: $SAMPLE_KEY"

# - name: Check Secret
#   image: alpine
#   environment:
#     SAMPLE_KEY:
#       from_secret: TEST_SECRET
#   commands:
#     - echo "Checking SAMPLE_KEY..."
#     - if [ -z "$SAMPLE_KEY" ]; then echo "SAMPLE_KEY is not set"; else echo "SAMPLE_KEY is set to: $SAMPLE_KEY"; fi


# ---
# kind: pipeline
# type: docker
# name: default

# platform:
#   os: linux
#   arch: arm64
  
# steps:
# - name: another
#   image: alpine
#   commands:
#   - echo "Hellos"
#   - sleep 2
#   - echo "Done"

# ---
# kind: signature
# hmac: F10E2821BBBEA527EA02200352313BC059445190
