---
kind: pipeline
name: test secret kubernetes

# platform:
#   os: linux
#   arch: amd64

steps:
- commands:
  - echo 12345678
  environment:
    SAMPLE_KEY:
      from_secret: FOO
  image: alpine
  name: Install Dependencies
- commands:
  - echo $${SAMPLE_KEY}
  environment:
    SAMPLE_KEY:
      from_secret: FOO
  image: alpine
  name: Run Linting
- commands:
  - echo $${SAMPLE_KEY}
  environment:
    SAMPLE_KEY:
      from_secret: FOO
  image: alpine
  name: Run Unit Tests
trigger:
  branch:
    exclude:
    - main
  event:
  - push
type: kubernetes
