name: Hello World Workflow

on:
  push:  # Trigger the workflow on any push event
  pull_request:  # Trigger the workflow on pull request events

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Say Hello
        run: echo "Hello world"

      - name: Print Secret
        run:  echo "My secret is ${{ secrets.CI12517 }}"
